jobs:
    build_app:
        steps:
    - id: s01
    run: echo "github ${{github.ref_name}}"
      - id: s02
          run: echo "before " && ls -l
          uses: actions/setup-node@v4
          with:
            node-version: 24
      
    